version: '3.0'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=vti
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/data/db
